qtopia-opensource-src-4.3.1

diff --git a/bin/assistant b/bin/assistant
--- a/bin/assistant
+++ b/bin/assistant
@@ -1,37 +1,4 @@
-#!/usr/bin/perl
-use strict;
-use warnings;
-
-use File::Glob;
-use File::Copy;
-use File::Path;
-use Cwd;
-use File::Basename;
-use lib ( dirname($0)."/../src/build/bin" );
-use Qtopia::Paths;
-use Qtopia::Vars;
-use Qtopia::File;
-
-Qtopia::Paths::get_paths();
-
-# Windows depot builds use the perl scripts directly rather than the compiled code
-if ( $isWindows ) {
-    check_script($0, "$depotpath/bin", $ARGV[0]);
-}
-
-# Load the Qtopia content files
-for my $file ( "$QPEDIR/doc/html/qtopia.dcf",
-               "$QPEDIR/doc/html/buildsystem/buildsystem.dcf",
-               "$QPEDIR/doc/html/qtopiadesktop/qtopiadesktop.dcf" ) {
-    if ( -f $file ) {
-        system("$DQTDIR/bin/assistant", "-addContentFile", $file);
-    }
-}
-
-my @cmd = ("$DQTDIR/bin/assistant", @ARGV);
-if ( $isWindows ) {
-    unshift(@cmd, "start", "/b");
-}
-my $ret = system(@cmd);
-exit $ret;
-
+#!/bin/sh
+# get the paths
+if [ -f "$(dirname $0)/../src/build/bin/getpaths.sh" ]; then . "$(dirname $0)/../src/build/bin/getpaths.sh"; else echo "Could not find getpaths.sh"; exit 1; fi
+exec "$QPEDIR/src/build/bin/assistant" "$@"
