qtopia-opensource-src-4.2.4

diff --git a/bin/mkPackages b/bin/mkPackages
--- a/bin/mkPackages
+++ b/bin/mkPackages
@@ -54,7 +54,7 @@ else
     if [ -z $ip ]; then
         die "URL looked wrong: $URL"
     fi
-    ping -c 1 -W 1 $ip | grep " 0% packet loss" 2>&1 >/dev/null || die "Something is wrong with the URL: $URL"
+    ping -c 1 -W 1 $ip | grep " 0% packet loss" 2>&1 >/dev/null || echo "Something is wrong with the URL: $URL. Could not ping $ip"
 fi
 
 # See if there's packages in this directory to be installed in the 
diff --git a/devices/greenphone/src/devtools/scripts/lan-network b/devices/greenphone/src/devtools/scripts/lan-network
--- a/devices/greenphone/src/devtools/scripts/lan-network
+++ b/devices/greenphone/src/devtools/scripts/lan-network
@@ -290,11 +290,15 @@ start()
     
     case $MODE in
         dhcp)
-            /sbin/udhcpc -i $1
+            # if you add parameters to /sbin/udhcpc below, alway leave "-i $1" last
+            if ! /sbin/udhcpc -n -t 10 -i $1; then
+                # failed to get a lease after 10 tries
+                stop $1
+            fi
             ;;
         static)
             /sbin/ifconfig $1 netmask $NETMASK broadcast $BROADCAST $IPADDR up
-            /sbin/route del default
+            /sbin/route del default 2>/dev/null
             /sbin/route add default gw $GATEWAY
             ;;
         *)
@@ -310,7 +314,7 @@ stop()
     print_debug "stopping interface $1";
 
     # stop udhcpc for interface
-    DHCP_PIDS=$( ps | grep "[u]dhcpc -i $1" | awk '{print $1}' )
+    DHCP_PIDS=$( ps | grep "[u]dhcpc .*-i $1" | awk '{print $1}' )
     [ -n "$DHCP_PIDS" ] && kill $DHCP_PIDS 2>&1 >/dev/null
 
     # stop wpa_supplicant for interface
@@ -346,12 +350,15 @@ route()
         gateway=$3
     else
         echo "Using DHCP information to find gateway IP";
-        ## ADD CODE HERE ##
+
+        # renew udhcpc for interface
+        DHCP_PIDS=$( ps | grep "[u]dhcpc .*-i $1" | awk '{print $1}' )
+        [ -n "$DHCP_PIDS" ] && kill -s SIGUSR1 $DHCP_PIDS 2>&1 >/dev/null
     fi
 
     if [ -n "$gateway" ]; then
         print_debug "removing old default route";
-        /sbin/route del default;
+        /sbin/route del default 2>/dev/null;
         print_debug "adding new default route via $1";
         /sbin/route add default gw $gateway;
     fi
@@ -385,3 +392,4 @@ case $ACTION in
         exit 1;
         ;;
 esac
+
diff --git a/scripts/greenphone-sdk/scripts/gph b/scripts/greenphone-sdk/scripts/gph
--- a/scripts/greenphone-sdk/scripts/gph
+++ b/scripts/greenphone-sdk/scripts/gph
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 . /opt/Qtopia/SDK/scripts/functions
 
@@ -29,7 +29,7 @@ gp_net()
 {
   # Bring up network to greenphone
 
-  sudo modprobe usbnet>/dev/null 2>&1
+  sudo modprobe usbnet >/dev/null 2>&1
   if [ "$DEVNODE" = "" ] ; then
     echo "Networking failed. Please unplug and plug the Greenphone back in."
     return 1;
@@ -41,7 +41,7 @@ gp_net()
   # Figure out the IP now that the device is up
   PHONEIP=`phoneip`
 
-  if ! ping -c 1 -i 2 $PHONEIP 1>/dev/null 2>&1 ; then
+  if ! ping -c 1 -i 2 $PHONEIP >/dev/null 2>&1 ; then
     echo "Networking failed. Please unplug and plug the Greenphone back in."
     return 1;
   fi
@@ -49,14 +49,20 @@ gp_net()
   if [ ! -f "$HOME/.ssh/id_dsa.pub" ]; then
     # generate keypair of ssh
     [ "$VERBOSE" = "1" ] && echo "Generating DSA keypair for ssh"
-    ssh-keygen -t dsa -N '' -f $HOME/.ssh/id_dsa 2>&1 >/dev/null
+    ssh-keygen -t dsa -N '' -f $HOME/.ssh/id_dsa >/dev/null 2>&1
   fi
 
   # send public key to Greenphone
-  if netcat -n $PHONEIP 10022 < $HOME/.ssh/id_dsa.pub; then
+  if netcat -n $PHONEIP 10022 < $HOME/.ssh/id_dsa.pub >/dev/null 2>&1; then
      [ "$VERBOSE" = "1" ] && echo "Sent DSA public key to Greenphone"
   else
      [ "$VERBOSE" = "1" ] && echo "Greenphone already has DSA public key."
+     
+     # test if we can connect to Greenphone
+     if ! ssh root@$PHONEIP /bin/true >/dev/null 2>&1; then
+       echo "Authentication failed. Run 'Devtools/Reqacquire Auth Key' on Greenphone."
+       return 1
+     fi
   fi
 
   if [ "$VERBOSE" = "1" ]; then
@@ -242,11 +248,11 @@ gp_run()
     fi
 if [ "$QDEBUG" = "-debug" ] ; then
 
-  ssh root@$PHONEIP "cd /; binary=\$(find . -name example 2>/dev/null | while read file; do if [ -x \$file ]; then echo \$file; exit; fi; done); gdbserver hostpc:22222 \$binary 2>&1 | logger -t 'DEBUGGER' &"
+  ssh root@$PHONEIP "cd /; binary=\$(find . -name example 2>/dev/null | while read file; do if [ -x \$file ] && [ -f \$file ]; then echo \$file; exit; fi; done); . /opt/Qtopia.rom/qpe.env; gdbserver hostpc:22222 \$binary 2>&1 | logger -t 'DEBUGGER' &"
 
 else
   
-  ssh root@$PHONEIP "cd /; binary=\$(find . -name example 2>/dev/null | while read file; do if [ -x \$file ]; then echo \$file; exit; fi; done); \$binary 2>&1 | logger -t 'DEBUGGER' &"
+  ssh root@$PHONEIP "cd /; binary=\$(find . -name example 2>/dev/null | while read file; do if [ -x \$file ] && [ -f \$file ]; then echo \$file; exit; fi; done); . /opt/Qtopia.rom/qpe.env; \$binary 2>&1 | logger -t 'DEBUGGER' &"
  
   fi
 fi
