qtopia-4.3.0

diff --git a/devices/greenphone/rootfs/basefiles/bin/updateqtopia b/devices/greenphone/rootfs/basefiles/bin/updateqtopia
--- a/devices/greenphone/rootfs/basefiles/bin/updateqtopia
+++ b/devices/greenphone/rootfs/basefiles/bin/updateqtopia
@@ -1,36 +1,26 @@
 #!/bin/sh
 
-# This flash script updates the Greenphone with a new Qtopia image,
-# by running trolltech_flash.sh in the update image.
+# This script updates the Greenphone with a new Qtopia image
 
 usage()
 {
     echo "Usage: $0 [options] <Qtopia image>"
-    echo "    --remove-flash-files    Remove flash files after upgrade"
-    echo "    --dont-reboot           Don't automatically reboot after upgrade"
-    echo "    --ignore-firstrun       Ignore firstrun file and always flash"
+    echo "    --force-flash           Force a reflash even if it is detected that the"
+    echo "                            installed image is the same as the update image"
     echo "    --no-questions          Don't ask any questions"
 }
 
 export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
 
 # Process command line options
-OPTION_REMOVE_FLASH_FILES=0
-OPTION_DONT_REBOOT=0
-OPTION_IGNORE_FIRSTRUN=0
+OPTION_FORCE_FLASH=0
 OPTION_NO_QUESTIONS=0
 QTOPIA_IMAGE_PATH=""
 
 while [ $# -gt 0 ]; do
     case $1 in
-        --remove-flash-files)
-            OPTION_REMOVE_FLASH_FILES=1
-            ;;
-        --dont-reboot)
-            OPTION_DONT_REBOOT=1
-            ;;
-        --ignore-firstrun)
-            OPTION_IGNORE_FIRSTRUN=1
+        --force-flash)
+            OPTION_FORCE_FLASH=1
             ;;
         --no-questions)
             OPTION_NO_QUESTIONS=1
@@ -57,8 +47,6 @@ fi
 
 cd "$QTOPIA_IMAGE_PATH"
 
-QTOPIA_FIRST_RUN=/mnt/user/tools/.firstrun
-
 # Path where status images are stored
 STATUS_IMAGE_PATH=/usr/share/updateqtopia
 
@@ -73,19 +61,68 @@ STATUS_IMAGES="flash-status-fail-fserror.gif \
                flash-status-flashing.gif \
                flash-status-pass.gif"
 
+# Block device where QTOPIA_IMAGE is installed to
+QTOPIA_IMAGE_DEVICE=/dev/tffsa2
+
 contains_update_image()
 {
-    for i in trolltech_flash.sh $QTOPIA_IMAGE $STATUS_IMAGES; do
+    # check for update image
+    for i in $QTOPIA_IMAGE $STATUS_IMAGES; do
         [ ! -r $QTOPIA_IMAGE_PATH/$i ] && return 1
     done
-    
     return 0
+}
+
+contains_old_update_image()
+{
+    # check for old update image
+    [ -f $QTOPIA_IMAGE_PATH/trolltech_flash.sh ]
+}
+
+check_free_space()
+{
+    # Find size of QTOPIA_IMAGE_DEVICE
+    local DEVICE=$(basename $QTOPIA_IMAGE_DEVICE)
+    if grep $DEVICE /proc/partitions >/dev/null; then
+        local AVAILABLE_SPACE=$(awk "/$DEVICE/ {print \$3}" /proc/partitions)
+    else
+        local AVAILABLE_SPACE=0
+    fi
+
+    local REQUIRED_SPACE=$(ls -s $QTOPIA_IMAGE_PATH/qtopia.cramfs | awk '{print $1}')
+
+    [ $AVAILABLE_SPACE -lt $REQUIRED_SPACE ]
+}
+
+same_update_image()
+{
+    # check if update image is different to installed image
+    # We use the first 48 bytes of the super block in qtopia.cramfs for this.
+    # The structure of the first 48 bytes of the cramfs super block is:
+    # Bytes     Description     Contents
+    # 0 - 3     Magic number    0x28cd3d45
+    # 4 - 7     Size            <variable>
+    # 8 - 11    Flags           0x00000003
+    # 12 - 15   Future          0x00000000
+    # 16 - 31   Signiture       "Compressed ROMSFS"
+    # 32 - 35   CRC             <variable>
+    # 36 - 39   Edition         0x00000000
+    # 40 - 43   Blocks          <variable>
+    # 44 - 47   Files           <variable>
+    INST_ID=$( hexdump -e '"%08x"' -n 48 $QTOPIA_IMAGE_DEVICE )
+    NEW_ID=$( hexdump -e '"%08x"' -n 48 $QTOPIA_IMAGE_PATH/$QTOPIA_IMAGE )
+
+    [ "$INST_ID" = "$NEW_ID" ]
 }
 
 flash_status()
 {
-    echo "TROLL: $2"
-    gifanim $STATUS_IMAGE_PATH/$1.gif
+    echo "Update Qtopia: $2"
+    if [ -f $QTOPIA_IMAGE_PATH/$1.gif ]; then
+        gifanim $QTOPIA_IMAGE_PATH/$1.gif
+    elif [ -f $STATUS_IMAGE_PATH/$1.gif ]; then
+        gifanim $STATUS_IMAGE_PATH/$1.gif
+    fi
 }
 
 question()
@@ -95,27 +132,32 @@ question()
     flash_status "$1" "$2"
 
     while true; do
-        KEYCODE=`getkeycode`
+        KEYCODE=$(getkeycode)
 
         [ "$KEYCODE" = "19" ] && return 0
         [ "$KEYCODE" = "26" ] && return 1
     done
 }
 
-###############################################
-# Greenphone Qtoipa Flash for SDK Development #
-###############################################
-
-[ $OPTION_IGNORE_FIRSTRUN -eq 1 ] && rm -f $QTOPIA_FIRST_RUN
-
-if [ -e $QTOPIA_FIRST_RUN ]; then
-    # this is the first boot after flashing
-    # don't reflash the device
-    rm -f $QTOPIA_FIRST_RUN
+if ! contains_update_image; then
+    echo "Update Qtopia: Update image not found"
     exit 1
 fi
 
-if ! contains_update_image; then
+if contains_old_update_image; then
+    flash_status flash-status-fail-fsversion "Old Update Qtopia image, not supported with this root filesystem"
+    sleep 30
+    exit 1
+fi
+
+if check_free_space; then
+    flash_status flash-status-fail-space "Insufficient space on system storage"
+    sleep 30
+    exit 1
+fi
+
+if same_update_image && [ $OPTION_FORCE_FLASH -eq 0 ]; then
+    echo "Update Qtopia: Update image already installed"
     exit 1
 fi
 
@@ -126,20 +168,12 @@ if [ $OPTION_NO_QUESTIONS -eq 0 ]; then
     fi
 fi
 
-# trolltech_flash expects the image to be mounted on /mnt/sd
-if [ "$QTOPIA_IMAGE_PATH" != "/mnt/sd" ]; then
-    mount -o bind $QTOPIA_IMAGE_PATH /mnt/sd
-fi
+flash_status flash-status-flashing "Installing new Qtopia image"
 
-[ $OPTION_REMOVE_FLASH_FILES -eq 1 ] && OPTIONS="--remove-files"
-[ $OPTION_DONT_REBOOT -eq 1 ] && OPTIONS="$OPTIONS --dont-reboot"
+dd if=$QTOPIA_IMAGE_PATH/$QTOPIA_IMAGE of=$QTOPIA_IMAGE_DEVICE bs=1M
 
-updateqtopiahelper flash $OPTIONS
-RETVAL=$?
+# Force LIDS rules to be regenerated at reboot
+rm -f /etc/lids/lids_initialized
 
-if [ "$QTOPIA_IMAGE_PATH" != "/mnt/sd" ]; then
-    umount /mnt/sd
-fi
-
-exit $RETVAL
+flash_status flash-status-pass "Qtopia update complete"
 
diff --git a/scripts/clean_qtopia b/scripts/clean_qtopia
--- a/scripts/clean_qtopia
+++ b/scripts/clean_qtopia
@@ -1,6 +1,6 @@
 #!/bin/sh
 # get the paths
-if [ -f "$(dirname $0)/getpaths.sh" ]; then . "$(dirname $0)/getpaths.sh"; else echo "Could not find getpaths.sh"; exit 1; fi
+if [ -f "$(dirname $0)/../src/build/bin/getpaths.sh" ]; then . "$(dirname $0)/../src/build/bingetpaths.sh"; else echo "Could not find getpaths.sh"; exit 1; fi
 
 win32=0
 image=0
diff --git a/scripts/greenphone-sdk/scripts/gph b/scripts/greenphone-sdk/scripts/gph
--- a/scripts/greenphone-sdk/scripts/gph
+++ b/scripts/greenphone-sdk/scripts/gph
@@ -30,6 +30,7 @@ gp_net()
   # Bring up network to greenphone
 
   sudo modprobe usbnet >/dev/null 2>&1
+  export DEVNODE=`greenphone_devnode`
   if [ "$DEVNODE" = "" ] ; then
     echo "Networking failed. Please unplug and plug the Greenphone back in."
     return 1;
@@ -42,7 +43,7 @@ gp_net()
   PHONEIP=`phoneip`
 
   if ! ping -c 1 -i 2 $PHONEIP >/dev/null 2>&1 ; then
-    echo "Networking failed. Please unplug and plug the Greenphone back in."
+    echo "Could not contact Greenphone at $PHONEIP. Please unplug and plug the Greenphone back in."
     return 1;
   fi
 
@@ -52,22 +53,14 @@ gp_net()
     ssh-keygen -t dsa -N '' -f $HOME/.ssh/id_dsa >/dev/null 2>&1
   fi
 
-  # send public key to Greenphone
-  if netcat -n $PHONEIP 10022 < $HOME/.ssh/id_dsa.pub >/dev/null 2>&1; then
-     [ "$VERBOSE" = "1" ] && echo "Sent DSA public key to Greenphone"
-  else
-     [ "$VERBOSE" = "1" ] && echo "Greenphone already has DSA public key."
-     
-     # test if we can connect to Greenphone
-     if ! ssh root@$PHONEIP /bin/true >/dev/null 2>&1; then
-       echo "Authentication failed. Run 'Devtools/Reqacquire Auth Key' on Greenphone."
-       return 1
-     fi
-  fi
-
-  if [ "$VERBOSE" = "1" ]; then
+  # attempt to connect to Greenphone
+  if ! ssh root@$PHONEIP /bin/true >/dev/null 2>&1; then
+    echo "Connection to Greenphone at $PHONEIP failed."
+    return 1
+  elif [ "$VERBOSE" = "1" ]; then
     echo "Success! Greenphone address is $PHONEIP"
   fi
+
   return 0;
 }
 
@@ -213,20 +206,22 @@ gp_install()
 			sudo cp -f pkg/$PKG $QPKWEBSERVER
 			sudo chmod 644 $QPKWEBSERVER/$PKG
 	done;
-  sudo /opt/Qtopia/SDK/scripts/mkPackages $QPKWEBSERVER --descriptors http://$HOSTIP
+  sudo /opt/Qtopia/SDK/scripts/mkPackages $QPKWEBSERVER --descriptors http://$HOSTIP/
 
   if [ "$ARCH" = "x86" ] ;then
     PATH=/opt/Qtopia/SDK/$QPEVER/x86/image/bin:$PATH
     for PKG in $LIST; do
       echo "Install process for ${PKG} successfully initiated"
-      qcop service send PackageManager 'installPackageConfirm(QString)' http://$HOSTIP/$PKG.qpd
+      PKGFILE=`echo $PKG|sed 's/.qpk//g'`
+      qcop service send PackageManager 'installPackageConfirm(QString)' http://$HOSTIP/$PKGFILE.qpd
     done;
   else
 
     for PKG in $LIST; do
       echo "Install process for ${PKG} successfully initiated"
+      PKGFILE=`echo $PKG|sed 's/.qpk//g'`
 
-      ssh root@$PHONEIP ". /opt/Qtopia.rom/qpe.env; qcop service send PackageManager 'installPackageConfirm(QString)' 'http://${HOSTIP}/${PKG}.qpd'; sleep 3; echo DONE;"
+      ssh root@$PHONEIP ". /opt/Qtopia/qpe.env; qcop service send PackageManager 'installPackageConfirm(QString)' 'http://${HOSTIP}/${PKGFILE}.qpd'; sleep 3; echo DONE;"
     done;
   fi
   return 0;
@@ -248,11 +243,11 @@ gp_run()
     fi
 if [ "$QDEBUG" = "-debug" ] ; then
 
-  ssh root@$PHONEIP "cd /; binary=\$(find . -name example 2>/dev/null | while read file; do if [ -x \$file ] && [ -f \$file ]; then echo \$file; exit; fi; done); . /opt/Qtopia.rom/qpe.env; gdbserver hostpc:22222 \$binary 2>&1 | logger -t 'DEBUGGER' &"
+  ssh root@$PHONEIP "cd /; binary=\$(find . -name example 2>/dev/null | while read file; do if [ -x \$file ] && [ -f \$file ]; then echo \$file; exit; fi; done); . /opt/Qtopia/qpe.env; gdbserver hostpc:22222 \$binary 2>&1 | logger -t 'DEBUGGER' &"
 
 else
   
-  ssh root@$PHONEIP "cd /; binary=\$(find . -name example 2>/dev/null | while read file; do if [ -x \$file ] && [ -f \$file ]; then echo \$file; exit; fi; done); . /opt/Qtopia.rom/qpe.env; \$binary 2>&1 | logger -t 'DEBUGGER' &"
+  ssh root@$PHONEIP "cd /; binary=\$(find . -name example 2>/dev/null | while read file; do if [ -x \$file ] && [ -f \$file ]; then echo \$file; exit; fi; done); . /opt/Qtopia/qpe.env; \$binary 2>&1 | logger -t 'DEBUGGER' &"
  
   fi
 fi
@@ -270,7 +265,7 @@ gp_rescan()
       return 1; 
     fi
 
- ssh root@$PHONEIP ". /opt/Qtopia.rom/qpe.env; qcop QPE/DocAPI 'scanPath(QString,int)' 'all' '1'; sleep 3; echo DONE;"
+ ssh root@$PHONEIP ". /opt/Qtopia/qpe.env; qcop QPE/DocAPI 'scanPath(QString,int)' 'all' '1'; sleep 3; echo DONE;"
 fi 
 }
 
diff --git a/scripts/greenphone-sdk/scripts/runqvfb-greenphone b/scripts/greenphone-sdk/scripts/runqvfb-greenphone
--- a/scripts/greenphone-sdk/scripts/runqvfb-greenphone
+++ b/scripts/greenphone-sdk/scripts/runqvfb-greenphone
@@ -15,21 +15,15 @@ if [ -e /tmp/qtembedded-$LOGNAME/QtEmbedded-$display ]; then
     exit 1;
 fi
 
-if [ -z "$QPEDIR" -a -d $PWD/qtopiacore/host/tools/qvfb ];then
+if [ -z "$QPEDIR" -a -d $PWD/src/tools/qt/qvfb ];then
     QPEDIR=$PWD
 fi
 
-if [ -d $QPEDIR/qtopiacore/host/tools/qvfb ]; then
-    cd $QPEDIR/qtopiacore/host/tools/qvfb
-elif [ -d $DQTDIR/tools/qvfb ]; then
-    cd $DQTDIR/tools/qvfb
+if [ -d $QPEDIR/src/tools/qt/qvfb ]; then
+    cd $QPEDIR/src/tools/qt/qvfb
 else
-    if which qvfb >/dev/null 2>&1; then
-	cd $(dirname $(which qvfb))
-    else
-	echo "Cannot find QVfb!"
-	exit 1
-    fi
+    echo "Cannot find QVfb!"
+    exit 1
 fi
 verbose=0
 while getopts "v" opt; do
@@ -39,17 +33,8 @@ while getopts "v" opt; do
             ;;
     esac
 done
-srcdir=$(dirname $(awk '/^# Project:/{print $3}' Makefile) 2>/dev/null)
-if [ -z "$srcdir" ]; then
-    qvfb=./qvfb
-else
-    qvfb=$(/bin/pwd)/qvfb
-    if [ "$verbose" = 1 ]; then
-        echo "Running from $srcdir"
-    fi
-    cd $srcdir
-fi
 shift $(expr $OPTIND - 1)
+qvfb=$QPEDIR/bin/qvfb
 args=
 skins="$QVFB_SKIN Trolltech-Keypad Trolltech-Touchscreen"
 if [ -f $1.skin -o -d $1.skin ]; then
@@ -63,9 +48,6 @@ do
         break
     fi
 done
-if [ ! -x "$qvfb" ]; then
-    qvfb=$QPEDIR/qtopiacore/host/bin/qvfb
-fi
 if [ "$verbose" = 1 ]; then
     echo $qvfb -qwsdisplay :$display $args
     $qvfb -qwsdisplay :$display $args "$@"
diff --git a/scripts/greenphone-sdk/scripts/updatedevice b/scripts/greenphone-sdk/scripts/updatedevice
--- a/scripts/greenphone-sdk/scripts/updatedevice
+++ b/scripts/greenphone-sdk/scripts/updatedevice
@@ -1,23 +1,41 @@
 #!/bin/sh
 
-. /opt/Qtopia/SDK/scripts/functions
+if [ -r /opt/Qtopia/SDK/scripts/functions ]; then
+    . /opt/Qtopia/SDK/scripts/functions
+    QPEVER=$(version)
+fi
 
-QPEVER=`version`
+die()
+{
+    echo -n "updatedevice failed while doing: "
+    echo $@
+    exit 1
+}
 
 prepare_device()
 {
-    ssh root@$PHONEIP 'updateqtopiahelper killqtopia'
-    ssh root@$PHONEIP 'updateqtopiahelper unmountqtopia'
-    ssh root@$PHONEIP 'gifanim /mnt/user/tools/splash.gif'
+    if ! ssh root@$PHONEIP 'cat /fs.ver' | grep '^troll v3\.[0123456789]*$' >/dev/null 2>&1; then
+        echo "Incompatible root filesystem detected.  Update Greenphone with USB Flash image."
+        echo "Refer to the Greenphone Quick Start Guide for flash instructions."
+        exit 1
+    fi
+
+    ssh root@$PHONEIP 'updateqtopiahelper killqtopia' || die prepare_device updateqtopiahelper killqtopia
+    ssh root@$PHONEIP 'updateqtopiahelper unmountqtopia' || die prepare_device updateqtopiahelper unmountqtopia
+
+    scp $TEMPDIR/flash-status-flashing.gif root@$PHONEIP:/tmp || die prepare_device scp
+
+    ssh root@$PHONEIP 'gifanim /tmp/flash-status-flashing.gif' || die prepare_device gifanim
+    ssh root@$PHONEIP 'rm -f /tmp/flash-status-flashing.gif' || die prepare_device rm
 }
 
 extract_image()
 {
-    tar -C $TEMPDIR -xzf $QTOPIA_IMAGE
+    tar -C $TEMPDIR -xzf $QTOPIA_IMAGE || die extract_image
 
     # check for flash.conf
     if [ -r $TEMPDIR/flash.conf ]; then
-        echo "USB Flash image detected.  Refer to the Greenphone Quick Start Guide for instructions."
+        echo "USB Flash image detected.  Refer to the Greenphone Quick Start Guide for flash instructions."
         exit 1
     fi
 }
@@ -26,25 +44,34 @@ upload_image()
 {
     IMAGE_SIZE=0
     for file in $TEMPDIR/*; do
-        IMAGE_SIZE=$(($IMAGE_SIZE + `stat -c %s $file`))
+        IMAGE_SIZE=$(($IMAGE_SIZE + $(stat -c %s $file)))
     done
     IMAGE_SIZE=$(( (1 + $IMAGE_SIZE / 1048576) * 1048576 ))
 
     MNTPNT=$( ssh root@$PHONEIP "updateqtopiahelper createtemp $IMAGE_SIZE" )
 
-    for i in $TEMPDIR/* ; do
-        scp $i root@$PHONEIP:$MNTPNT
-    done
+    if [ -z $MNTPNT ]; then
+        echo "Error creating temporary directory on Greenphone, aborting"
+        exit 1
+    fi
+
+    scp $TEMPDIR/* root@$PHONEIP:$MNTPNT || die upload_image
 }
 
 install_image()
 {
-    ssh root@$PHONEIP "updateqtopia --no-questions --ignore-firstrun --dont-reboot $MNTPNT"
-    ssh root@$PHONEIP "updateqtopiahelper deletetemp $MNTPNT"
-    ssh root@$PHONEIP "reboot"
+    ssh root@$PHONEIP "updateqtopia --no-questions $MNTPNT" >/dev/null
+    RESULT=$?
+    ssh root@$PHONEIP "updateqtopiahelper deletetemp $MNTPNT" || die install_image updateqtopiahelper
+
+    if [ $RESULT -ne 0 ]; then
+        sleep 60
+    fi
+    ssh root@$PHONEIP "reboot" || die install_image reboot
 }
 
-if [ $# -eq 0 ]; then
+# Find default update image
+if [ $# -eq 0 ] && [ -r /opt/Qtopia/extras/images/qtopia-greenphone-update.tar.gz ]; then
     QTOPIA_IMAGE=/opt/Qtopia/extras/images/qtopia-greenphone-update.tar.gz
 elif [ $# -eq 1 ]; then    
     case "$1" in
@@ -52,7 +79,7 @@ elif [ $# -eq 1 ]; then
             QTOPIA_IMAGE="$1"
             ;;
         *)
-            QTOPIA_IMAGE="`pwd`/$1"
+            QTOPIA_IMAGE="$(pwd)/$1"
             ;;
     esac
 else
@@ -60,19 +87,34 @@ else
     exit 1
 fi
 
-TEMPDIR=`mktemp -d /tmp/updatedevice.XXXXXX`
+# Check if network is up
+if which gph >/dev/null 2>&1; then
+    # SDK 
+    if ! gph -net; then
+        echo "Could not establish a network connection with Greenphone.  Check connection."
+        exit 1
+    fi
+else
+    # not SDK
+    if [ -z $PHONEIP ]; then
+        PHONEIP=10.10.10.20
+    fi
+
+    if ! ssh root@$PHONEIP /bin/true >/dev/null 2>&1; then
+        echo "Could not establish a network connection with Greenphone at $PHONEIP.  Check connection."
+        exit 1
+    fi
+fi
+
+TEMPDIR=$(mktemp -d /tmp/updatedevice.XXXXXX)
 trap 'rm -rf $TEMPDIR' 0
 
-if gph -net; then
-  echo "Network up, continue with flash"
-else
-  exit
-fi
+# Flash Process
 echo "Starting Flash process, please wait..."
-prepare_device
-echo "device prep stage complete."
 extract_image
 echo "extract stage complete."
+prepare_device
+echo "device prep stage complete."
 upload_image
 echo "uploading image stage complete."
 echo
