Qtopia rsync of july 2nd 2008. The first available snapshot after license cleanups

diff --git a/devices/ficgta01/src/devtools/scripts/lan-network b/devices/ficgta01/src/devtools/scripts/lan-network
--- a/devices/ficgta01/src/devtools/scripts/lan-network
+++ b/devices/ficgta01/src/devtools/scripts/lan-network
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# This script has been customized for the C3200 Zaurus
+# This script has been customized for the Greenphone.
 
 # The dialup plugin uses the 'lan-network' script in order to access/install
 # system dependent options. System integrators must provide such a script 
@@ -14,12 +14,12 @@
 # into the image directory.
 #
 # For further details how this script is used 
-# see $QPEDIR/src/plugins/network/lan/lan.cpp.
+# see $QPEDIR/src/plugins/network/lan/lan.cpp and the Network Services documentation.
 
 
 ###############################
 DEBUG=1
-LOG=0
+LOG=1
 LOG_FILE="/tmp/qtopia-network.log"
 TMP_FILE="/tmp/lan-intern-network.temp";
 RESOLVCONF="/etc/resolv.conf"
@@ -56,6 +56,17 @@ print_options()
     exit 1;
 }
 
+update_hosts()
+{
+    TMPHOSTS=$(mktemp /etc/hosts.XXXXXX)
+    awk -v interface=$1 -v ipaddress=$2 '
+        BEGIN {done = 0}
+        $2 == interface {printf "%s\t%s\n", ipaddress, $2 ; done = 1}
+        $2 != interface {print $0}
+        END { if (done == 0) printf "%s\t%s\n", ipaddress, interface }' /etc/hosts > $TMPHOSTS
+    mv -f $TMPHOSTS /etc/hosts
+}
+
 
 # install network configuration and dns server
 # parameter: 
@@ -72,7 +83,9 @@ print_options()
 #                       * [-authmode <open|shared> -multikey <defaultKey> <key1> <key2> <key3> <key4>] 
 #                       * [-authmode <open|shared> -phrase <passphrase> ]   
 #                       * [-authmode <none> -nokey ]  
-#                       * [-authmode <WPA-PSK|WPA-EAP> <password> ]
+#                       * [-authmode <WPA-PSK> <password> <TKIP|AES> ]
+#                       * [-authmode <WPA-EAP> <TLS> <identity> <client-key-password> <clientKey> <clientCert> <serverCert>
+#                       * [-authmode <WPA-EAP> <TTLS|PEAP> <identity> <password> <serverCert> <MD5|GTC|MSCHAPV2|Any> <anonymous identity>
  
 install()
 {
@@ -99,7 +112,7 @@ install()
                echo > $TMP_FILE
             fi
 
-            mv $TMP_FILE /etc/resolvconf/$IFACE
+            mv -f $TMP_FILE /etc/resolvconf/$IFACE
 
             rm -f $RESOLVCONF
             ln -s /etc/resolvconf/$IFACE $RESOLVCONF
@@ -133,83 +146,127 @@ install()
 
             mkdir -p $HOME/Settings/Network/wireless
             NET_OPTIONS=$HOME/Settings/Network/wireless/$IFACE
-            echo > $NET_OPTIONS
+            echo > $TMP_FILE
 
             while [ $# -gt 0 ]; do
+print_debug "$1" 
                 case "$1" in 
                     -mode)
                         shift;
-                        echo "WIRELESS_MODE='$1'" >> $NET_OPTIONS
+                        echo "WIRELESS_MODE='$1'" >> $TMP_FILE;
                         ;;
                     -essid)
                         shift;
-                        WIRELESS_ESSID=$1
-                        echo "WIRELESS_ESSID=$1" >> $NET_OPTIONS
+                        echo "WIRELESS_ESSID=$1" >> $TMP_FILE;
                         ;;
                     -ap)
                         shift;
-                        echo "WIRELESS_AP=$1" >> $NET_OPTIONS
+                        echo "WIRELESS_AP=$1" >> $TMP_FILE;
                         ;;
                     -bitrate)
                         shift;
                         if [ "$1" = "0" ]; then
-                            echo "WIRELESS_BITRATE='auto'" >> $NET_OPTIONS
-                            echo "auto detect bitrate"
+                            echo "WIRELESS_BITRATE='auto'" >> $TMP_FILE;
                         else
-                            echo "WIRELESS_BITRATE='$1'" >> $NET_OPTIONS
-                            echo "use given bitrate";
+                            echo "WIRELESS_BITRATE='$1'" >> $TMP_FILE;
                         fi  
                         ;;
                     -nick)
                         shift;
-                        echo "WIRELESS_NICK='$1'" >> $NET_OPTIONS
+                        echo "WIRELESS_NICK='$1'" >> $TMP_FILE;
                         ;;
                     -channel)
                         shift;
                         if [ "$1" = "0" ]; then
-                            echo "WIRELESS_CHANNEL=''" >> $NET_OPTIONS
-                            echo "auto detect channel";
+                            echo "WIRELESS_CHANNEL=''" >> $TMP_FILE;
                         else
-                            echo "WIRELESS_CHANNEL='$1'" >> $NET_OPTIONS
-                            echo "use given channel";
+                            echo "WIRELESS_CHANNEL='$1'" >> $TMP_FILE;
                         fi
                         ;;
                     -keylength)
                         shift;
-                        echo "WIRELESS_KEY_LENGTH='$1'" >> $NET_OPTIONS
+                        echo "WIRELESS_KEY_LENGTH='$1'" >> $TMP_FILE;
                         ;;
                     -authmode)
                         shift;
-                        echo "WIRELESS_AUTH_MODE=$1" >> $NET_OPTIONS
                         case "$1" in 
                             open|shared|none)
-                                ## ADD CODE HERE ##
+                                echo "WIRELESS_AUTH_MODE=NONE" >> $TMP_FILE;
                                 # handle open/shared/none encryptipon
                                 shift;
+                                local ka kb kc kd="";
                                 if [ "$1" = "-phrase" ]; then
                                     shift;
-                                    ## ADD CODE HERE ##
-                                    echo "use passphrase";
+                                    print_debug "use passphrase";
+                                     echo "WIRELESS_DEFAULT_KEY='0'" >> $TMP_FILE;
+                                     echo "WIRELESS_WEP_PHRASE=$1"  >> $TMP_FILE;
+
                                 elif [ "$1" = "-nokey" ]; then
                                     shift;
-                                    ## ADD CODE HERE ##
                                     print_debug "no password/keys given";
                                 elif [ "$1" = "-multikey" ]; then
                                     shift;
-                                    echo "using default key: $1" # can be 0-3
-                                    ## ADD CODE HERE ##
+                                    echo "WIRELESS_DEFAULT_KEY='$1'" >> $TMP_FILE;
                                     shift;
-                                    ## ADD CODE HERE ##
-                                    # read all 4 keys and determine which is default
+                                    ka=$(echo $1 | tr -d :)
+                                    shift;
+                                    kb=$(echo $1 | tr -d :)
+                                    shift;
+                                    kc=$(echo $1 | tr -d :)
+                                    shift;
+                                    kd=$(echo $1 | tr -d :)
+                                echo "WIRELESS_KEY_0=$ka" >> $TMP_FILE;
+                                echo "WIRELESS_KEY_1=$kb" >> $TMP_FILE;
+                                echo "WIRELESS_KEY_2=$kc" >> $TMP_FILE;
+                                echo "WIRELESS_KEY_3=$kd" >> $TMP_FILE;
                                 fi
                                 ;;
                             WPA-PSK)
+                                echo "WIRELESS_AUTH_MODE=WPA-PSK" >> $TMP_FILE;
                                 shift;
-                                echo "WIRELESS_PSK=$1" >> $NET_OPTIONS
+                                echo "WIRELESS_WPA_PSK=$1" >> $TMP_FILE;
+                                shift;
+                                case "$1" in
+                                    TKIP)
+                                        echo "WIRELESS_PAIRWISE=TKIP" >> $TMP_FILE;
+                                        echo "WIRELESS_GROUP=TKIP" >> $TMP_FILE;
+                                        ;;
+                                    AES)
+                                        echo "WIRELESS_PAIRWISE=CCMP" >> $TMP_FILE;
+                                        echo "WIRELESS_GROUP=CCMP" >> $TMP_FILE;
+                                        ;;
+                                esac
                                 ;;
                             WPA-EAP)
+                                echo "WIRELESS_AUTH_MODE=WPA-EAP" >> $TMP_FILE;
                                 shift;
-                                ## ADD CODE HERE ##
+                                mode=$1;
+                                echo "WIRELESS_EAP_MODE=$mode" >> $TMP_FILE;
+                                shift;
+                                echo "WIRELESS_WPA_IDENTITY='$1'" >> $TMP_FILE;
+                                shift;
+                                if [ "$mode" = "TLS" ]; then
+                                    echo "WIRELESS_CLIENT_KEY_PASSWORD='$1'" >> $TMP_FILE;
+                                    shift;
+                                    echo "WIRELESS_CLIENT_KEY='$1'" >> $TMP_FILE;
+                                    shift;
+                                    echo "WIRELESS_CLIENT_CERT='$1'" >> $TMP_FILE;
+                                    shift;
+                                    echo "WIRELESS_CA_CERT='$1'" >> $TMP_FILE;
+                                    shift;
+                                else #PEAP and TTLS
+                                    echo "WIRELESS_WPA_PASSWORD='$1'" >> $TMP_FILE;
+                                    shift;
+                                    echo "WIRELESS_CA_CERT='$1'" >> $TMP_FILE;
+                                    shift;
+                                    echo "WIRELESS_EAP_AUTH='$1'" >> $TMP_FILE;
+                                    shift;
+                                    echo "WIRELESS_WPA_ANONID='$1'" >> $TMP_FILE;
+                                fi
+                                ;;
+                            *)
+                                print_debug "Unknown option: $1"
+                                shift;
                                 ;;
                         esac
                         ;;
@@ -221,6 +278,8 @@ install()
                 esac;
                 [ $# -gt 0 ] && shift;
             done
+
+            mv -f $TMP_FILE $NET_OPTIONS;
             ;;
         *)
             print_debug "Unknown option: $MODE";
@@ -247,48 +306,87 @@ start()
         # Generating wpa_supplicant.conf
         [ -d /var/lib/wpa_supplicant ] || mkdir -p /var/lib/wpa_supplicant
         WPACONF=/var/lib/wpa_supplicant/wpa_supplicant.conf
-        echo "network={" > $WPACONF
-        [ -n "$WIRELESS_ESSID" ] && echo "    ssid=\"$WIRELESS_ESSID\"" >> $WPACONF
-        echo "    proto=WPA2 WPA RSN" >> $WPACONF
-        [ -n "$WIRELESS_AUTH_MODE" ] && echo "    key_mgmt=$WIRELESS_AUTH_MODE" >> $WPACONF
-        echo "    pairwise=CCMP TKIP" >> $WPACONF
-        echo "    group=CCMP TKIP" >> $WPACONF
-        [ -n "$WIRELESS_PSK" ] && echo "    psk=\"$WIRELESS_PSK\"" >> $WPACONF
-        echo "}" >> $WPACONF
+        echo > $WPACONF
         
-        /sbin/ifconfig $1 down
+        echo "ap_scan=2" >> $WPACONF
+        echo "network={" >> $WPACONF
+        [ -n "$WIRELESS_ESSID" ] && echo "    ssid=\"$WIRELESS_ESSID\"" >> $WPACONF
+        [ -n "$WIRELESS_AUTH_MODE" ] && echo "    key_mgmt=$WIRELESS_AUTH_MODE" >> $WPACONF
+        [ -n "$WIRELESS_PAIRWISE" ] && echo "    pairwise=$WIRELESS_PAIRWISE" >> $WPACONF
+        [ -n "$WIRELESS_GROUP" ] && echo "    group=$WIRELESS_GROUP" >> $WPACONF
+        # WPA-PSK
+        [ -n "$WIRELESS_WPA_PSK" ] && echo "    psk=\"$WIRELESS_WPA_PSK\"" >> $WPACONF
+        # WEP
+        [ -n "$WIRELESS_KEY_0" ] && echo "    wep_key0=$WIRELESS_KEY_0" >> $WPACONF
+        if [ -n "$WIRELESS_WEP_PHRASE" ]; then
+						echo "    wep_key0=\"$WIRELESS_WEP_PHRASE\"" >> $WPACONF; 
+				else 
+						echo "    proto=WPA2 WPA RSN" >> $WPACONF
+				fi
+
+        [ -n "$WIRELESS_KEY_1" ] && echo "    wep_key0=$WIRELESS_KEY_1" >> $WPACONF
+        [ -n "$WIRELESS_KEY_2" ] && echo "    wep_key0=$WIRELESS_KEY_2" >> $WPACONF
+        [ -n "$WIRELESS_KEY_3" ] && echo "    wep_key0=$WIRELESS_KEY_3" >> $WPACONF
+        [ -n "$WIRELESS_DEFAULT_KEY" ] && echo "    wep_tx_keyidx=$WIRELESS_DEFAULT_KEY" >> $WPACONF
+        # WPA-EAP
+        [ -n "$WIRELESS_EAP_MODE" ] && echo "    eap=$WIRELESS_EAP_MODE" >> $WPACONF
+        [ -n "$WIRELESS_WPA_IDENTITY" ] && echo "    identity=\"$WIRELESS_WPA_IDENTITY\"" >> $WPACONF
+        [ -n "$WIRELESS_CLIENT_KEY" ] && echo "    private_key=\"$WIRELESS_CLIENT_KEY\"" >> $WPACONF
+        [ -n "$WIRELESS_CLIENT_KEY_PASSWORD" ] && echo "    private_key_passwd=\"$WIRELESS_CLIENT_KEY_PASSWORD\"" >> $WPACONF
+        [ -n "$WIRELESS_CLIENT_CERT" ] && echo "    client_cert=\"$WIRELESS_CLIENT_CERT\"" >> $WPACONF
+        [ -n "$WIRELESS_CA_CERT" ] && echo "    ca_cert=\"$WIRELESS_CA_CERT\"" >> $WPACONF
+        [ -n "$WIRELESS_WPA_PASSWORD" ] && echo "    password=\"$WIRELESS_WPA_PASSWORD\"" >> $WPACONF
+        [ -n "$WIRELESS_EAP_AUTH" ] && echo "    phase2=\"auth=$WIRELESS_EAP_AUTH\"" >> $WPACONF
+        [ -n "$WIRELESS_WPA_ANONID" ] && echo "    anonymous_identity=\"$WIRELESS_WPA_ANONID\"" >> $WPACONF
+        echo "}" >> $WPACONF
+        print_debug "stop/start interface";
+#        /sbin/ifconfig $1 down
         /sbin/ifconfig $1 up
 
-        if [ "$WIRELESS_ESSID" == "" ]; then
-           WIRELESS_ESSID = "any"
+        if [ "$WIRELESS_ESSID" != "" ]; then
+            /sbin/iwconfig $1 essid "$WIRELESS_ESSID"
+        else
+            /sbin/iwconfig $1 essid any
         fi
 
-        if [ "$WIRELESS_AP" == "" ]; then
-				  WIRELESS_AP = "any"
+        if [ "$WIRELESS_AP" != "" ]; then
+            /sbin/iwconfig $1 ap $WIRELESS_AP
+        else
+            /sbin/iwconfig $1 ap any
         fi
 
         if [ "$WIRELESS_BITRATE" != "" ] && [ "$WIRELESS_BITRATE" != "auto" ]; then
-            WIRELESS_BITRATE = "${WIRELESS_BITRATE}M auto"
+            /sbin/iwconfig $1 rate ${WIRELESS_BITRATE} auto
         else
-            WIRELESS_BITRATE = "auto"
+            /sbin/iwconfig $1 rate auto
+        fi
+       
+        if [ "$WIRELESS_NICK" != "" ]; then
+            /sbin/iwconfig $1 nick "$WIRELESS_NICK"
         fi
 
-#        if [ "$WIRELESS_CHANNEL" != "" ]; then
-#            /sbin/iwconfig $1 channel $WIRELESS_CHANNEL
-#        fi
-        
-        if [ "$WIRELESS_AUTH_MODE" = "WPA-PSK" ]; then
-            /sbin/wpa_supplicant -i $1 -D socketcf -c $WPACONF -B
+        if [ "$WIRELESS_CHANNEL" != "" ]; then
+            /sbin/iwconfig $1 channel $WIRELESS_CHANNEL
+        fi
+
+        if [ "$WIRELESS_WEP_PHRASE" != "" ]; then
+            /sbin/iwconfig $1 enc "s:$WIRELESS_WEP_PHRASE"
+				else
+						/usr/sbin/wpa_supplicant -i $1 -D wext -c $WPACONF -dd | logger -t WPA &
         fi
     fi
-
-/sbin/iwconfig $1 essid "$WIRELESS_ESSID" ap "$WIRELESS_AP" channel "$WIRELESS_CHANNEL" rate "$WIRELESS_BITRATE" nick "$WIRELESS_NICK"
-
+    
     case $MODE in
         dhcp)
-            /sbin/udhcpc -i $1 &
+            # if you add parameters to /sbin/udhcpc below, always leave "-i $1" last
+            print_debug "dhcp"
+            if ! /sbin/udhcpc -n -i $1; then
+                # failed to get a lease after 10 tries
+                stop $1
+            fi
             ;;
         static)
+            print_debug "static"
             /sbin/ifconfig $1 netmask $NETMASK broadcast $BROADCAST $IPADDR up
             /sbin/route del default
             /sbin/route add default gw $GATEWAY
@@ -306,11 +404,12 @@ stop()
     print_debug "stopping interface $1";
 
     # stop udhcpc for interface
-    DHCP_PIDS=$( ps | grep "[u]dhcpc -i $1" | awk '{print $1}' )
+    DHCP_PIDS=$( ps | grep "udhcpc .*-i $1" | awk '{print $1}' )
     [ -n "$DHCP_PIDS" ] && kill $DHCP_PIDS 2>&1 >/dev/null
+    #killall udhcpc
 
     # stop wpa_supplicant for interface
-    WPASUP_PIDS=$( ps | grep "[w]pa_supplicant -i $1" | awk '{print $1}' )
+    WPASUP_PIDS=$( ps | grep "wpa_supplicant -i $1" | awk '{print $1}' )
     [ -n "$WPASUP_PIDS" ] && kill $WPASUP_PIDS 2>&1 >/dev/null
     
     # bring down interface
@@ -337,17 +436,18 @@ route()
     print_debug "changing default route"
     
     if [ $# -gt 2 ]; then
-        ## ADD CODE HERE ##
         # gateway address was passed to us
         gateway=$3
     else
         echo "Using DHCP information to find gateway IP";
-        ## ADD CODE HERE ##
+        # renew udhcpc for interface
+        DHCP_PIDS=$( ps | grep "[u]dhcpc .*-i $1" | awk '{print $1}' )
+        [ -n "$DHCP_PIDS" ] && kill -s SIGUSR1 $DHCP_PIDS 2>&1 >/dev/null
     fi
 
     if [ -n "$gateway" ]; then
         print_debug "removing old default route";
-        /sbin/route del default;
+        /sbin/route del default 2>/dev/null;
         print_debug "adding new default route via $1";
         /sbin/route add default gw $gateway;
     fi
@@ -377,6 +477,7 @@ case $ACTION in
         route "$@";
         ;;
     *)
+        print_debug "Unknown option: $ACTION";
         print_options;
         exit 1;
         ;;
